#
#    GoMinewrap config file.
#

# Do not change.
version: "0.3"
server:
    # Enter the path to the folder with all your servers
    base: "servers/"
    # Enter the primary/main server here. CaSe SeNsItIvE (deprecated)
    primary: "hub"
    # Add all your servers here.
    servers:
        # The server's name.
        hub:
            # The server's name.
            # Enable or disable automatic server startup when the program is launched. [true/false]
            enabled: true
            # Enter the path to the server's root directory. Continuing from the base directory.
            dir: "hub/"
            # Startup script for the server.
            startup: "java -Xmx512M -jar spigot.jar"
        # The server's name.
        minigames:
            # Enable or disable automatic server startup when the program is launched. [true/false]
            enabled: true
            # Enter the path to the server's root directory. Continuing from the base directory.
            dir: "minigames/"
            # Startup script for the server.
            startup: "java -Xmx512M -jar spigot.jar"
    filters:
        # Enable or disable the custom filters. [true/false]
        enabled: true
    # Options for the backup command.
    backup:
        # Enter the path where the backup files will be placed. This dose not include the base directory.
        dir: "backups/"
web:
    # Enable or disable the web interface. [true/false]
    enabled: true
    # Enter the path to webcon's html files.
    dir: "static/web/html/"
    # Which host will webcon run on.
    host: ""
    # Which port will webcon run on.
    port: "25465"
    # Add as many users you want here for the webcon login.
    # format: username:password (password in sha256)
    users:
        - "admin:057ba03d6c44104863dc7361fe4578965d1887360f90a0895882e58a6248fc86"
